version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    versioning-strategy: "increase"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
